/**
 * Este archivo contiene versiones históricas de enums que pueden ser necesarios
 * para migraciones o compatibilidad con código antiguo.
 *
 * NO UTILIZAR EN CÓDIGO NUEVO - Solo para referencia en migraciones y código legacy.
 */

/**
 * Versión original de TherapistVerticalsEnum (pre-2025)
 */
export enum TherapistVerticalsEnumV1 {
    CLINIC = "CLINIC",
    SCHOOL = "SCHOOL",
    HOSPITAL = "HOSPITAL",
    COMMUNITY_CENTER = "COMMUNITY_CENTER",
    PRIVATE_PRACTICE = "PRIVATE_PRACTICE",
    REMOTE = "REMOTE",
    REHABILITATION_CENTER = "REHABILITATION_CENTER",
    EDUCATIONAL_INSTITUTION = "EDUCATIONAL_INSTITUTION",
    CORPORATE = "CORPORATE",
    HOME_CARE = "HOME_CARE",
    ONLINE = "ONLINE",
    WORKSHOPS = "WORKSHOPS",
    RESEARCH = "RESEARCH",
    NEW_PROJECTS = "NEW_PROJECTS",
}

/**
 * Versión original de TherapyTypeEnum (pre-2025)
 */
export enum TherapyTypeEnumV1 {
    INDIVIDUAL = "INDIVIDUAL",
    FAMILY = "FAMILY",
    GROUP = "GROUP",
    COUPLES = "COUPLES",
    COGNITIVE_BEHAVIORAL = "COGNITIVE_BEHAVIORAL",
    PSYCHODYNAMIC = "PSYCHODYNAMIC",
    HUMANISTIC = "HUMANISTIC",
    INTEGRATIVE = "INTEGRATIVE",
    TRAUMA_FOCUSED = "TRAUMA_FOCUSED",
    ONLINE = "ONLINE",
    PLAY_THERAPY = "PLAY_THERAPY",
    ART_THERAPY = "ART_THERAPY",
    MUSIC_THERAPY = "MUSIC_THERAPY",
    DIALECTICAL_BEHAVIOR = "DIALECTICAL_BEHAVIOR",
}

/**
 * Versión original de PopulationAgeRangeEnum (pre-2025)
 */
export enum PopulationAgeRangeEnumV1 {
    INFANTS = "INFANTS",
    EARLY_CHILDHOOD = "EARLY_CHILDHOOD",
    MIDDLE_CHILDHOOD = "MIDDLE_CHILDHOOD",
    ADOLESCENTS = "ADOLESCENTS",
    YOUNG_ADULTS = "YOUNG_ADULTS",
    ADULTS = "ADULTS",
    SENIORS = "SENIORS",
    CHILDREN_ALL = "CHILDREN_ALL",
    ADULTS_ALL = "ADULTS_ALL",
    ALL_AGES = "ALL_AGES",
}

/**
 * Versión original de TherapistSpecialtyEnum (pre-2025)
 */
export enum TherapistSpecialtyEnumV1 {
    PSYCHOLOGY = "PSYCHOLOGY",
    SPEECH_THERAPY = "SPEECH_THERAPY",
    OCCUPATIONAL_THERAPY = "OCCUPATIONAL_THERAPY",
    PHYSICAL_THERAPY = "PHYSICAL_THERAPY",
    PSYCHIATRY = "PSYCHIATRY",
    NEUROPSYCHOLOGY = "NEUROPSYCHOLOGY",
    CLINICAL_PSYCHOLOGY = "CLINICAL_PSYCHOLOGY",
    CHILD_PSYCHOLOGY = "CHILD_PSYCHOLOGY",
    GERIATRIC_PSYCHOLOGY = "GERIATRIC_PSYCHOLOGY",
    SPORTS_PSYCHOLOGY = "SPORTS_PSYCHOLOGY",
    EDUCATIONAL_PSYCHOLOGY = "EDUCATIONAL_PSYCHOLOGY",
    PEDIATRIC_THERAPY = "PEDIATRIC_THERAPY",
    FAMILY_THERAPY = "FAMILY_THERAPY",
    REHABILITATION = "REHABILITATION",
    COUNSELING = "COUNSELING",
}
